### ISSUE TITLE
Parser: JSON body should be JSON rather than String

### ISSUE THREAD

**Issue by six5536** [getMoreBrain/bitmark-parser-generator#153]
Bit

```
[.table]
{"Test": 100, "Test2": "Json"}

```

==>

```json
[
  {
    "bit": {
      "type": "table",
      "format": "json",
      "body": "{\"Test\": 100, \"Test2\": \"Json\"}"
    },
  }
]
```

There are 2 problems:
1.  the consumer has to parse the outer JSON, then parser the inner JSON string as JSON. This is less efficient than parsing the entire object as JSON.
2. JSON in the string has to be escaped, increasing the size of the data

==>

```json
[
  {
    "bit": {
      "type": "table",
      "format": "json",
      "body": {
        "Test": 100, 
        "Test2": "Json"
      }
    },
  }
]
```

**Comment by gaba-getmorebrain** [comment]
@zx-ncoderz Interesting idea. However, this is only possible if the JSON is validated.
Otherwise invalid JSON would allow for code injection. Efficiency will be probably destroyed as the JSON/string conversion methods are highly optimized (in machine code). Also, the additional formatting tabs need more space than the escaping. Of course, they could be omitted.

A benchmark would be needed to clarify these things.

However, I like the idea from different points of view. It just makes sense. Including validating the JSON anyway.
