### ISSUE TITLE
Support `@spaceId:...` tag for book bit

### ISSUE THREAD

**Issue by stefanszasz** [getMoreBrain/bitmark-parser-generator#31]
**Is your feature request related to a problem? Please describe.**
Book bits should support `@spaceId:..` tag.

**Describe the solution you'd like**

Parsing the following
```
[.book]
[@spaceId:sl]
[@language:de]
[#Book title]
```

Should not return any parsing warnings or errors when encountering @spaceId tag. It should treat it as any regular (array) tag:

```
"spaceId": ["sl"]
```

@gaba-getmorebrain

**Comment by zx-ncoderz** [comment]
@gaba-getmorebrain I am aware of this, but how would we like to handle it.

You mentioned before the @property properties are usually for testing, and otherwise they are well defined (in which case I can define them in the parser and they will work fine).

The problem with allowing any @property is converting JSON -> bitmark. It make the backwards mapping very difficult as any tag in the JSON could be an @property.

There is already an option that you can use 'includeExtraProperties' that will include the extra properties in the JSON output, but it won't suppress the warnings.

```
[.book]
[@spaceId:sl]
[@language:de]
[#Book title]
```

==>

```json
[
  {
    "bit": {
      "type": "book",
      "format": "bitmark--",
      "language": [
        "de"
      ],
      "title": "Book title",
      "item": "",
      "hint": "",
      "example": "",
      "isExample": false,
      "body": "",
      "spaceId": [
        "sl"
      ]
    },
    "parser": {
      "version": "1.0.8",
      "bitmarkVersion": "3",
      "warnings": [
        {
          "message": "'Property' with key 'spaceId' is an unexpected property. It is not included in the output by default",
          "text": "[@spaceId:sl]",
          "location": {
            "start": {
              "line": 2,
              "column": 1,
              "offset": 8
            },
            "end": {
              "line": 2,
              "column": 14,
              "offset": 21
            }
          }
        }
      ]
    },
    "bitmark": "[.book]\n[@spaceId:sl]\n[@language:de]\n[#Book title]"
  }
]
```

My proposal would be that we add known properties explicitly, and allow unknown properties, but with a flag.

Please let me know what you think and how I should proceed.

@stefanszasz, for now just using the 'includeExtraProperties' flag will solve this problem for you.

**Comment by zx-ncoderz** [comment]
So, now:
- unknown properties are included in the JSON by default
- unknown properties can be excluded from the JSON using the 'excludeUnknownProperties' flag
- Parser warnings are exluded by default, and can be enabled using the 'enableWarnings' flag

**Comment by zx-ncoderz** [comment]
Released in https://github.com/getMoreBrain/bitmark-parser-generator/releases/tag/v1.0.11
